// src/Features/Admin/constants/productSpecs.js

export const PRODUCT_CATEGORIES = {
  PC_BUILD: "pc-build",
  LAPTOP: "laptop",
  CPU: "cpu",
  MAINBOARD: "mainboard",
  RAM: "ram",
  VGA: "vga",
  SSD: "ssd",
  HDD: "hdd",
  PSU: "psu",
  CASE: "case",
  COOLING: "cooling",
  MONITOR: "monitor",
  KEYBOARD: "keyboard",
  MOUSE: "mouse",
};

// Template specs cho từng loại sản phẩm
export const SPECS_TEMPLATES = {
  // PC Build (cấu hình hoàn chỉnh)
  [PRODUCT_CATEGORIES.PC_BUILD]: [
    { key: "mainboard", label: "Mainboard", type: "text", required: true },
    { key: "cpu", label: "CPU", type: "text", required: true },
    { key: "ram", label: "RAM", type: "text", required: true },
    { key: "vga", label: "VGA - Card đồ họa", type: "text", required: false },
    { key: "ssd", label: "SSD", type: "text", required: false },
    { key: "hdd", label: "HDD", type: "text", required: false },
    { key: "psu", label: "PSU - Nguồn", type: "text", required: true },
    { key: "case", label: "Case - Vỏ máy", type: "text", required: true },
    { key: "cooling", label: "Tản nhiệt", type: "text", required: false },
  ],

  // LAPTOP
  [PRODUCT_CATEGORIES.LAPTOP]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Dell Inspiron 15 3520",
    },
    // === CPU ===
    {
      key: "cpu",
      label: "CPU",
      type: "text",
      required: true,
      placeholder: "Intel Core i5-1235U / AMD Ryzen 7 7445H",
    },
    {
      key: "cpuSpeed",
      label: "Tốc độ CPU",
      type: "text",
      required: false,
      placeholder: "1.40 GHz upto 4.80 GHz",
    },
    {
      key: "cpuCores",
      label: "Số nhân; luồng",
      type: "text",
      required: false,
      placeholder: "16 nhân 22 luồng",
    },
    {
      key: "cpuCache",
      label: "Bộ nhớ Cache",
      type: "text",
      required: false,
      placeholder: "24MB Intel® Smart Cache",
    },
    // === RAM ===
    {
      key: "ram",
      label: "RAM",
      type: "text",
      required: true,
      placeholder: "16GB DDR5-5600 MT/s",
    },
    {
      key: "ramSlots",
      label: "Số khe RAM",
      type: "text",
      required: false,
      placeholder: "2x SO-DIMM / Onboard",
    },
    {
      key: "maxRam",
      label: "RAM tối đa hỗ trợ",
      type: "text",
      required: false,
      placeholder: "64GB",
    },
    // === Ổ cứng ===
    {
      key: "storage",
      label: "Ổ cứng",
      type: "text",
      required: true,
      placeholder: "512GB PCIe NVMe SSD Gen4",
    },
    {
      key: "storageSlots",
      label: "Khe ổ cứng",
      type: "text",
      required: false,
      placeholder: "1 slot M.2, max 2TB",
    },
    // === Card đồ họa ===
    {
      key: "vga",
      label: "Card đồ họa",
      type: "text",
      required: true,
      placeholder: "NVIDIA® GeForce RTX™ 4050 6GB GDDR6",
    },
    // === Màn hình ===
    {
      key: "display",
      label: "Màn hình",
      type: "text",
      required: true,
      placeholder: '15.6" FHD (1920x1080) IPS, 144Hz, 300 nits',
    },
    {
      key: "refreshRate",
      label: "Tần số quét",
      type: "text",
      required: false,
      placeholder: "144Hz",
    },
    {
      key: "panelType",
      label: "Loại panel",
      type: "select",
      options: ["IPS", "VA", "TN", "OLED"],
      required: false,
    },
    {
      key: "brightness",
      label: "Độ sáng",
      type: "text",
      required: false,
      placeholder: "300 nits / 400 nits",
    },
    {
      key: "colorGamut",
      label: "Không gian màu",
      type: "text",
      required: false,
      placeholder: "100% DCI-P3 / 45% NTSC",
    },
    // === Pin & Sạc ===
    {
      key: "battery",
      label: "Pin",
      type: "text",
      required: false,
      placeholder: "76Whr Li-ion / 46.8 Whrs 3 cell",
    },
    // === Kích thước & Trọng lượng ===
    {
      key: "weight",
      label: "Trọng lượng",
      type: "text",
      required: false,
      placeholder: "1.8kg",
    },
    {
      key: "dimensions",
      label: "Kích thước",
      type: "text",
      required: false,
      placeholder: "358.5 x 235.6 x 18.9mm",
    },
    // === Hệ điều hành ===
    {
      key: "os",
      label: "Hệ điều hành",
      type: "text",
      required: false,
      placeholder: "Windows 11 Home Single Language",
    },
    // === Cổng kết nối ===
    {
      key: "ports",
      label: "Cổng giao tiếp",
      type: "text",
      required: false,
      placeholder: "2x USB 3.2, 1x USB-C, 1x HDMI 2.1, 1x RJ45, 1x Audio Jack",
    },
    // === Kết nối không dây ===
    {
      key: "wifi",
      label: "Chuẩn WiFi",
      type: "text",
      required: false,
      placeholder: "Wi-Fi 6E 802.11ax / Killer™ Wi-Fi 6E",
    },
    {
      key: "bluetooth",
      label: "Bluetooth",
      type: "text",
      required: false,
      placeholder: "Bluetooth 5.3",
    },
    {
      key: "lan",
      label: "Chuẩn LAN",
      type: "text",
      required: false,
      placeholder: "10/100/1000 GbE LAN",
    },
    // === Thiết bị ngoại vi ===
    {
      key: "webcam",
      label: "Webcam",
      type: "text",
      required: false,
      placeholder: "FHD Camera / HD 720p",
    },
    {
      key: "keyboard",
      label: "Bàn phím",
      type: "text",
      required: false,
      placeholder: "Full-size backlit keyboard with numeric keypad",
    },
    {
      key: "audio",
      label: "Audio",
      type: "text",
      required: false,
      placeholder: "2x 2W Stereo Speakers / DTS:X Ultra",
    },
    // === Thiết kế ===
    {
      key: "color",
      label: "Màu sắc",
      type: "text",
      required: false,
      placeholder: "Steel Gray / Urban Silver",
    },
    {
      key: "material",
      label: "Chất liệu",
      type: "text",
      required: false,
      placeholder: "Cover A/C/D: Aluminum; Cover B: Plastic",
    },
    // === Bảo mật ===
    {
      key: "security",
      label: "Bảo mật",
      type: "text",
      required: false,
      placeholder: "Firmware TPM / Fingerprint Reader / BIOS Password",
    },
    // === Bảo hành ===
    {
      key: "warranty",
      label: "Bảo hành",
      type: "text",
      required: false,
      placeholder: "24 tháng",
    },
  ],

  // CPU
  [PRODUCT_CATEGORIES.CPU]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Intel Core i5-13400 / AMD Ryzen 5 7600",
    },
    {
      key: "generation",
      label: "Thế hệ",
      type: "text",
      required: false,
      placeholder: "Intel thế hệ 13 / AMD Zen 4",
    },
    {
      key: "socket",
      label: "Socket",
      type: "text",
      required: true,
      placeholder: "LGA 1700 / AM5",
    },
    // === Nhân & Luồng ===
    {
      key: "cores",
      label: "Số nhân",
      type: "text",
      required: true,
      placeholder: "10 (6P+4E) / 6",
    },
    {
      key: "threads",
      label: "Số luồng",
      type: "text",
      required: true,
      placeholder: "16 / 12",
    },
    {
      key: "performanceCores",
      label: "Số lõi hiệu năng (P-cores)",
      type: "text",
      required: false,
      placeholder: "6 lõi",
    },
    {
      key: "efficientCores",
      label: "Số lõi hiệu suất (E-cores)",
      type: "text",
      required: false,
      placeholder: "4 lõi",
    },
    // === Tốc độ ===
    {
      key: "baseClock",
      label: "Xung nhịp cơ bản",
      type: "text",
      required: true,
      placeholder: "2.5 GHz / 3.8 GHz",
    },
    {
      key: "boostClock",
      label: "Xung nhịp Turbo",
      type: "text",
      required: true,
      placeholder: "4.6 GHz / 5.1 GHz",
    },
    {
      key: "performanceClock",
      label: "Tốc độ lõi hiệu năng",
      type: "text",
      required: false,
      placeholder: "2.5 GHz Turbo up to 4.6 GHz",
    },
    {
      key: "efficientClock",
      label: "Tốc độ lõi hiệu suất",
      type: "text",
      required: false,
      placeholder: "1.8 GHz Turbo up to 3.3 GHz",
    },
    // === Bộ nhớ đệm ===
    {
      key: "cacheL2",
      label: "Bộ nhớ đệm L2",
      type: "text",
      required: false,
      placeholder: "9.5 MB / 6 MB",
    },
    {
      key: "cacheL3",
      label: "Bộ nhớ đệm L3",
      type: "text",
      required: true,
      placeholder: "20 MB / 32 MB",
    },
    {
      key: "totalCache",
      label: "Tổng Cache",
      type: "text",
      required: false,
      placeholder: "20 MB Intel Smart Cache",
    },
    // === TDP ===
    {
      key: "baseTDP",
      label: "Công suất cơ bản (TDP)",
      type: "text",
      required: false,
      placeholder: "65W",
    },
    {
      key: "maxTDP",
      label: "Công suất tối đa",
      type: "text",
      required: false,
      placeholder: "154W",
    },
    // === Bộ nhớ hỗ trợ ===
    {
      key: "memoryType",
      label: "Loại bộ nhớ hỗ trợ",
      type: "text",
      required: false,
      placeholder: "DDR5-4800 / DDR4-3200 / DDR5-5200",
    },
    {
      key: "maxMemory",
      label: "Dung lượng RAM tối đa",
      type: "text",
      required: false,
      placeholder: "128GB / 192GB",
    },
    {
      key: "memoryChannels",
      label: "Số kênh bộ nhớ",
      type: "text",
      required: false,
      placeholder: "2 kênh",
    },
    {
      key: "memoryBandwidth",
      label: "Băng thông bộ nhớ tối đa",
      type: "text",
      required: false,
      placeholder: "76.8 GB/s",
    },
    // === Đồ họa tích hợp ===
    {
      key: "integratedGraphics",
      label: "Đồ họa tích hợp",
      type: "text",
      required: false,
      placeholder: "Intel UHD 730 / AMD Radeon Graphics",
    },
    {
      key: "gpuBaseClock",
      label: "Tần số GPU cơ bản",
      type: "text",
      required: false,
      placeholder: "300 MHz",
    },
    {
      key: "gpuBoostClock",
      label: "Tần số GPU tối đa",
      type: "text",
      required: false,
      placeholder: "1.55 GHz",
    },
    {
      key: "gpuOutputs",
      label: "Đầu ra đồ họa",
      type: "text",
      required: false,
      placeholder: "eDP 1.4b, DP 1.4a, HDMI 2.1",
    },
    {
      key: "maxResolution",
      label: "Độ phân giải tối đa",
      type: "text",
      required: false,
      placeholder: "HDMI: 4096x2160@60Hz, DP: 7680x4320@60Hz",
    },
    {
      key: "directXSupport",
      label: "Hỗ trợ DirectX",
      type: "text",
      required: false,
      placeholder: "DirectX 12",
    },
    {
      key: "openGLSupport",
      label: "Hỗ trợ OpenGL",
      type: "text",
      required: false,
      placeholder: "OpenGL 4.5",
    },
    // === PCI Express ===
    {
      key: "pciVersion",
      label: "Phiên bản PCI Express",
      type: "text",
      required: false,
      placeholder: "PCIe 5.0 / PCIe 4.0",
    },
    {
      key: "pciLanes",
      label: "Số làn PCI Express",
      type: "text",
      required: false,
      placeholder: "20 lanes / 24 lanes",
    },
    {
      key: "pciConfig",
      label: "Cấu hình PCI Express",
      type: "text",
      required: false,
      placeholder: "Up to 1x16+4, 2x8+4",
    },
    // === Khác ===
    {
      key: "unlocked",
      label: "Mở khóa ép xung",
      type: "select",
      options: ["Có (K/KF/X/XT)", "Không"],
      required: false,
    },
    {
      key: "coolerIncluded",
      label: "Tản nhiệt đi kèm",
      type: "text",
      required: false,
      placeholder: "Không có / AMD Wraith Stealth",
    },
    {
      key: "architecture",
      label: "Kiến trúc",
      type: "text",
      required: false,
      placeholder: "Raptor Lake / Zen 4",
    },
    {
      key: "manufacturing",
      label: "Tiến trình sản xuất",
      type: "text",
      required: false,
      placeholder: "Intel 7 (10nm) / TSMC 5nm",
    },
  ],

  // Mainboard
  [PRODUCT_CATEGORIES.MAINBOARD]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "ASUS PRIME H610M-A",
    },
    {
      key: "chipset",
      label: "Chipset",
      type: "text",
      required: true,
      placeholder: "H610M",
    },
    {
      key: "socket",
      label: "Socket",
      type: "text",
      required: true,
      placeholder: "LGA 1700",
    },
    {
      key: "formFactor",
      label: "Form Factor",
      type: "select",
      options: ["ATX", "Micro-ATX", "Mini-ITX", "E-ATX"],
      required: true,
    },
    {
      key: "ramSlots",
      label: "Số khe RAM",
      type: "number",
      required: true,
      placeholder: "2",
    },
    {
      key: "maxRam",
      label: "RAM tối đa",
      type: "text",
      required: true,
      placeholder: "64GB",
    },
    {
      key: "ramType",
      label: "Loại RAM",
      type: "select",
      options: ["DDR4", "DDR5"],
      required: true,
    },
    {
      key: "m2Slots",
      label: "Số khe M.2",
      type: "number",
      required: false,
      placeholder: "1",
    },
    {
      key: "sataSlots",
      label: "Số khe SATA",
      type: "number",
      required: false,
      placeholder: "4",
    },
    { key: "wifi", label: "WiFi", type: "checkbox", required: false },
    { key: "bluetooth", label: "Bluetooth", type: "checkbox", required: false },
  ],

  // RAM
  [PRODUCT_CATEGORIES.RAM]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "V-Color Skywalker Plus",
    },
    {
      key: "type",
      label: "Loại RAM",
      type: "select",
      options: ["DDR3", "DDR4", "DDR5"],
      required: true,
    },
    {
      key: "capacity",
      label: "Dung lượng",
      type: "text",
      required: true,
      placeholder: "16GB",
    },
    {
      key: "speed",
      label: "Tốc độ",
      type: "text",
      required: true,
      placeholder: "3600MHz",
    },
    {
      key: "cas",
      label: "CAS Latency",
      type: "text",
      required: false,
      placeholder: "CL18",
    },
    {
      key: "modules",
      label: "Số module",
      type: "select",
      options: ["1x", "2x", "4x"],
      required: true,
    },
    { key: "rgb", label: "RGB", type: "checkbox", required: false },
  ],

  // VGA (Card đồ họa)
  [PRODUCT_CATEGORIES.VGA]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "ASUS Dual Radeon RX 6500 XT",
    },
    {
      key: "chipset",
      label: "Chipset",
      type: "text",
      required: true,
      placeholder: "RX 6500 XT",
    },
    {
      key: "vram",
      label: "VRAM",
      type: "text",
      required: true,
      placeholder: "4GB GDDR6",
    },
    {
      key: "busWidth",
      label: "Bus width",
      type: "text",
      required: false,
      placeholder: "128-bit",
    },
    {
      key: "coreClock",
      label: "Core Clock",
      type: "text",
      required: false,
      placeholder: "2310MHz",
    },
    {
      key: "boostClock",
      label: "Boost Clock",
      type: "text",
      required: false,
      placeholder: "2825MHz",
    },
    {
      key: "tdp",
      label: "TDP",
      type: "text",
      required: false,
      placeholder: "130W",
    },
    {
      key: "powerConnectors",
      label: "Nguồn phụ",
      type: "text",
      required: false,
      placeholder: "1x 8-pin",
    },
    {
      key: "outputs",
      label: "Cổng xuất hình",
      type: "text",
      required: false,
      placeholder: "3x DP, 1x HDMI",
    },
  ],

  // SSD
  [PRODUCT_CATEGORIES.SSD]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "PNY CS900",
    },
    {
      key: "capacity",
      label: "Dung lượng",
      type: "text",
      required: true,
      placeholder: "250GB",
    },
    {
      key: "interface",
      label: "Giao tiếp",
      type: "select",
      options: ["SATA 3", "M.2 NVMe", "M.2 SATA"],
      required: true,
    },
    {
      key: "formFactor",
      label: "Form Factor",
      type: "text",
      required: false,
      placeholder: "2280",
    },
    {
      key: "readSpeed",
      label: "Tốc độ đọc",
      type: "text",
      required: false,
      placeholder: "3500MB/s",
    },
    {
      key: "writeSpeed",
      label: "Tốc độ ghi",
      type: "text",
      required: false,
      placeholder: "3000MB/s",
    },
    {
      key: "nand",
      label: "Loại NAND",
      type: "text",
      required: false,
      placeholder: "TLC",
    },
  ],

  // HDD
  [PRODUCT_CATEGORIES.HDD]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Seagate Barracuda",
    },
    {
      key: "capacity",
      label: "Dung lượng",
      type: "text",
      required: true,
      placeholder: "1TB",
    },
    {
      key: "rpm",
      label: "Tốc độ vòng quay",
      type: "text",
      required: true,
      placeholder: "7200RPM",
    },
    {
      key: "cache",
      label: "Bộ nhớ đệm",
      type: "text",
      required: false,
      placeholder: "64MB",
    },
    {
      key: "interface",
      label: "Giao tiếp",
      type: "text",
      required: true,
      placeholder: "SATA 3",
    },
    {
      key: "formFactor",
      label: "Form Factor",
      type: "select",
      options: ['3.5"', '2.5"'],
      required: true,
    },
  ],

  // PSU (Nguồn)
  [PRODUCT_CATEGORIES.PSU]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "FSP HV PRO 550W",
    },
    {
      key: "wattage",
      label: "Công suất",
      type: "text",
      required: true,
      placeholder: "550W",
    },
    {
      key: "certification",
      label: "Chứng nhận",
      type: "select",
      options: [
        "80 Plus",
        "80 Plus Bronze",
        "80 Plus Silver",
        "80 Plus Gold",
        "80 Plus Platinum",
        "80 Plus Titanium",
      ],
      required: true,
    },
    {
      key: "modular",
      label: "Dây rời",
      type: "select",
      options: ["Non-Modular", "Semi-Modular", "Full-Modular"],
      required: true,
    },
    {
      key: "formFactor",
      label: "Form Factor",
      type: "text",
      required: false,
      placeholder: "ATX",
    },
  ],

  // Case (Vỏ máy)
  [PRODUCT_CATEGORIES.CASE]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Xigmatek QUANTUM 4AF",
    },
    {
      key: "formFactor",
      label: "Form Factor",
      type: "select",
      options: ["Full Tower", "Mid Tower", "Mini Tower", "Mini-ITX"],
      required: true,
    },
    {
      key: "mainboardSupport",
      label: "Hỗ trợ mainboard",
      type: "text",
      required: true,
      placeholder: "ATX, Micro-ATX, Mini-ITX",
    },
    {
      key: "maxGpuLength",
      label: "Chiều dài VGA tối đa",
      type: "text",
      required: false,
      placeholder: "350mm",
    },
    {
      key: "maxCpuCoolerHeight",
      label: "Chiều cao tản nhiệt tối đa",
      type: "text",
      required: false,
      placeholder: "165mm",
    },
    {
      key: "expansionSlots",
      label: "Số khe mở rộng",
      type: "number",
      required: false,
      placeholder: "7",
    },
    {
      key: "fans",
      label: "Quạt đi kèm",
      type: "text",
      required: false,
      placeholder: "4x 120mm",
    },
    { key: "rgb", label: "RGB", type: "checkbox", required: false },
  ],

  // Cooling (Tản nhiệt)
  [PRODUCT_CATEGORIES.COOLING]: [
    { key: "model", label: "Model", type: "text", required: true },
    {
      key: "type",
      label: "Loại",
      type: "select",
      options: ["Air Cooler", "AIO Liquid", "Custom Loop"],
      required: true,
    },
    {
      key: "fanSize",
      label: "Kích thước quạt",
      type: "text",
      required: false,
      placeholder: "120mm",
    },
    {
      key: "height",
      label: "Chiều cao",
      type: "text",
      required: false,
      placeholder: "158mm",
    },
    {
      key: "socketSupport",
      label: "Socket hỗ trợ",
      type: "text",
      required: false,
      placeholder: "LGA 1700, AM4, AM5",
    },
    {
      key: "tdp",
      label: "TDP",
      type: "text",
      required: false,
      placeholder: "180W",
    },
    { key: "rgb", label: "RGB", type: "checkbox", required: false },
  ],

  // Monitor - ✅ ĐÃ CẬP NHẬT ĐẦY ĐỦ
  [PRODUCT_CATEGORIES.MONITOR]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "AOC 24G2",
    },
    {
      key: "size",
      label: "Kích thước",
      type: "text",
      required: true,
      placeholder: "24 inch",
    },
    {
      key: "resolution",
      label: "Độ phân giải",
      type: "text",
      required: true,
      placeholder: "Full HD (1920x1080)",
    },
    {
      key: "panel",
      label: "Tấm nền",
      type: "select",
      options: ["IPS", "VA", "TN", "OLED", "Mini-LED"],
      required: true,
    },
    {
      key: "screenType",
      label: "Kiểu màn hình",
      type: "text",
      required: true,
      placeholder: "Phẳng / Cong 1800R",
    },
    {
      key: "refreshRate",
      label: "Tần số quét",
      type: "text",
      required: true,
      placeholder: "180 Hz",
    },
    {
      key: "responseTime",
      label: "Thời gian phản hồi",
      type: "text",
      required: true,
      placeholder: "1ms GtG",
    },
    {
      key: "brightness",
      label: "Độ sáng (Typ.)",
      type: "text",
      required: false,
      placeholder: "250 cd/m²",
    },
    {
      key: "colorSpace",
      label: "Không gian màu (sRGB)",
      type: "text",
      required: false,
      placeholder: "135%",
    },
    {
      key: "ports",
      label: "Cổng kết nối",
      type: "text",
      required: false,
      placeholder: "1x HDMI; 1x DisplayPort 1.4",
    },
    {
      key: "vesaMount",
      label: "Tương thích VESA",
      type: "text",
      required: false,
      placeholder: "100 x 100mm",
    },
    {
      key: "flickerFree",
      label: "Khử nhấp nháy",
      type: "select",
      options: ["Có", "Không"],
      required: false,
    },
    {
      key: "warranty",
      label: "Bảo hành",
      type: "text",
      required: false,
      placeholder: "36 Tháng",
    },
    {
      key: "accessories",
      label: "Phụ kiện trong hộp",
      type: "text",
      required: false,
      placeholder: "Dây nguồn; dây HDMI; dây DisplayPort",
    },
    // === THÔNG SỐ BỔ SUNG ===
    {
      key: "adaptiveSync",
      label: "Công nghệ đồng bộ hóa",
      type: "text",
      required: false,
      placeholder: "G-SYNC / FreeSync",
    },
    {
      key: "aspectRatio",
      label: "Tỉ lệ khung hình",
      type: "text",
      required: false,
      placeholder: "16:9 / 21:9 / 32:9",
    },
    {
      key: "displayColors",
      label: "Màu hiển thị",
      type: "text",
      required: false,
      placeholder: "16.7M (8 bit) / 1073.7M (10 bit)",
    },
    {
      key: "contrastRatio",
      label: "Tỷ lệ tương phản (Typ.)",
      type: "text",
      required: false,
      placeholder: "1000:1 / 1,500,000:1",
    },
    {
      key: "surfaceType",
      label: "Bề mặt hiển thị",
      type: "select",
      options: ["Chống lóa", "Bóng"],
      required: false,
    },
    {
      key: "mechanicalDesign",
      label: "Thiết kế cơ học",
      type: "text",
      required: false,
      placeholder: "Nghiêng: -5°~+20°; Quay: ±15°; Điều chỉnh độ cao: 0-100mm",
    },
    {
      key: "weight",
      label: "Trọng lượng",
      type: "text",
      required: false,
      placeholder: "5.2 kg",
    },
    {
      key: "packageDimensions",
      label: "Kích thước đóng gói",
      type: "text",
      required: false,
      placeholder: "60 x 50 x 20 cm",
    },
  ],

  // Keyboard
  [PRODUCT_CATEGORIES.KEYBOARD]: [
    { key: "model", label: "Model", type: "text", required: true },
    {
      key: "type",
      label: "Loại",
      type: "select",
      options: ["Mechanical", "Membrane", "Optical"],
      required: true,
    },
    {
      key: "switch",
      label: "Switch",
      type: "text",
      required: false,
      placeholder: "Cherry MX Red",
    },
    {
      key: "layout",
      label: "Layout",
      type: "select",
      options: ["Full-size", "TKL", "60%", "65%", "75%"],
      required: true,
    },
    {
      key: "connection",
      label: "Kết nối",
      type: "select",
      options: ["Wired", "Wireless", "2.4G + Bluetooth", "Tri-mode"],
      required: true,
    },
    { key: "rgb", label: "RGB", type: "checkbox", required: false },
    { key: "hotSwap", label: "Hot-swap", type: "checkbox", required: false },
  ],

  // Mouse
  [PRODUCT_CATEGORIES.MOUSE]: [
    { key: "model", label: "Model", type: "text", required: true },
    {
      key: "sensor",
      label: "Cảm biến",
      type: "text",
      required: false,
      placeholder: "Optical",
    },
    {
      key: "dpi",
      label: "DPI",
      type: "text",
      required: true,
      placeholder: "16000",
    },
    {
      key: "connection",
      label: "Kết nối",
      type: "select",
      options: ["Wired", "Wireless", "2.4G + Bluetooth", "Tri-mode"],
      required: true,
    },
    {
      key: "weight",
      label: "Trọng lượng",
      type: "text",
      required: false,
      placeholder: "70g",
    },
    { key: "rgb", label: "RGB", type: "checkbox", required: false },
  ],
};

// Danh sách categories để dropdown
export const CATEGORY_OPTIONS = [
  {
    value: PRODUCT_CATEGORIES.PC_BUILD,
    label: "🖥️ PC Build (Cấu hình hoàn chỉnh)",
  },
  { value: PRODUCT_CATEGORIES.LAPTOP, label: "💻 Laptop" },
  { value: PRODUCT_CATEGORIES.CPU, label: "🔲 CPU - Bộ vi xử lý" },
  { value: PRODUCT_CATEGORIES.MAINBOARD, label: "🔧 Mainboard - Bo mạch chủ" },
  { value: PRODUCT_CATEGORIES.RAM, label: "💾 RAM - Bộ nhớ" },
  { value: PRODUCT_CATEGORIES.VGA, label: "🎮 VGA - Card đồ họa" },
  { value: PRODUCT_CATEGORIES.SSD, label: "💿 SSD" },
  { value: PRODUCT_CATEGORIES.HDD, label: "💿 HDD" },
  { value: PRODUCT_CATEGORIES.PSU, label: "🔌 PSU - Nguồn" },
  { value: PRODUCT_CATEGORIES.CASE, label: "📦 Case - Vỏ máy" },
  { value: PRODUCT_CATEGORIES.COOLING, label: "❄️ Cooling - Tản nhiệt" },
  { value: PRODUCT_CATEGORIES.MONITOR, label: "🖥️ Monitor - Màn hình" },
  { value: PRODUCT_CATEGORIES.KEYBOARD, label: "⌨️ Keyboard - Bàn phím" },
  { value: PRODUCT_CATEGORIES.MOUSE, label: "🖱️ Mouse - Chuột" },
];
