// src/Features/Admin/constants/productSpecs.js

export const PRODUCT_CATEGORIES = {
  PC: "pc",
  LAPTOP: "laptop",
  CPU: "cpu",
  MAINBOARD: "mainboard",
  RAM: "ram",
  VGA: "vga",
  STORAGE: "storage",
  PSU: "psu",
  CASE: "case",
  COOLING: "cooling",
  MONITOR: "monitor",
  KEYBOARD: "keyboard",
  MOUSE: "mouse",
  CHAIR: "chair", // 🆕 GHẾ
  HEADPHONE: "headphone", // 🆕 TAI NGHE
  SPEAKER: "speaker", // 🆕 LOA
  ACCESSORY: "accessories", //phụ kiện
  SOFTWARE: "software",
};

// Template specs cho từng loại sản phẩm
export const SPECS_TEMPLATES = {
  // PC Build (cấu hình hoàn chỉnh)
  [PRODUCT_CATEGORIES.PC]: [
    { key: "mainboard", label: "Mainboard", type: "text", required: true },
    { key: "cpu", label: "CPU", type: "text", required: true },
    { key: "ram", label: "RAM", type: "text", required: true },
    { key: "vga", label: "VGA - Card đồ họa", type: "text", required: false },
    { key: "ssd", label: "SSD", type: "text", required: false },
    { key: "hdd", label: "HDD", type: "text", required: false },
    { key: "psu", label: "PSU - Nguồn", type: "text", required: true },
    { key: "case", label: "Case - Vỏ máy", type: "text", required: true },
    { key: "cooling", label: "Tản nhiệt", type: "text", required: false },
  ],

  // LAPTOP
  [PRODUCT_CATEGORIES.LAPTOP]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Dell Inspiron 15 3520",
    },
    // === CPU ===
    {
      key: "cpu",
      label: "CPU",
      type: "text",
      required: true,
      placeholder: "Intel Core i5-1235U / AMD Ryzen 7 7445H",
    },
    {
      key: "cpuSpeed",
      label: "Tốc độ CPU",
      type: "text",
      required: false,
      placeholder: "1.40 GHz upto 4.80 GHz",
    },
    {
      key: "cpuCores",
      label: "Số nhân; luồng",
      type: "text",
      required: false,
      placeholder: "16 nhân 22 luồng",
    },
    {
      key: "cpuCache",
      label: "Bộ nhớ Cache",
      type: "text",
      required: false,
      placeholder: "24MB Intel® Smart Cache",
    },
    // === RAM ===
    {
      key: "ram",
      label: "RAM",
      type: "text",
      required: true,
      placeholder: "16GB DDR5-5600 MT/s",
    },
    {
      key: "ramSlots",
      label: "Số khe RAM",
      type: "text",
      required: false,
      placeholder: "2x SO-DIMM / Onboard",
    },
    {
      key: "maxRam",
      label: "RAM tối đa hỗ trợ",
      type: "text",
      required: false,
      placeholder: "64GB",
    },
    // === Ổ cứng ===
    {
      key: "storage",
      label: "Ổ cứng",
      type: "text",
      required: true,
      placeholder: "512GB PCIe NVMe SSD Gen4",
    },
    {
      key: "storageSlots",
      label: "Khe ổ cứng",
      type: "text",
      required: false,
      placeholder: "1 slot M.2, max 2TB",
    },
    // === Card đồ họa ===
    {
      key: "vga",
      label: "Card đồ họa",
      type: "text",
      required: true,
      placeholder: "NVIDIA® GeForce RTX™ 4050 6GB GDDR6",
    },
    // === Màn hình ===
    {
      key: "display",
      label: "Màn hình",
      type: "text",
      required: true,
      placeholder: '15.6" FHD (1920x1080) IPS, 144Hz, 300 nits',
    },
    {
      key: "refreshRate",
      label: "Tần số quét",
      type: "text",
      required: false,
      placeholder: "144Hz",
    },
    {
      key: "panelType",
      label: "Loại panel",
      type: "select",
      options: ["IPS", "VA", "TN", "OLED"],
      required: false,
    },
    {
      key: "brightness",
      label: "Độ sáng",
      type: "text",
      required: false,
      placeholder: "300 nits / 400 nits",
    },
    {
      key: "colorGamut",
      label: "Không gian màu",
      type: "text",
      required: false,
      placeholder: "100% DCI-P3 / 45% NTSC",
    },
    // === Pin & Sạc ===
    {
      key: "battery",
      label: "Pin",
      type: "text",
      required: false,
      placeholder: "76Whr Li-ion / 46.8 Whrs 3 cell",
    },
    // === Kích thước & Trọng lượng ===
    {
      key: "weight",
      label: "Trọng lượng",
      type: "text",
      required: false,
      placeholder: "1.8kg",
    },
    {
      key: "dimensions",
      label: "Kích thước",
      type: "text",
      required: false,
      placeholder: "358.5 x 235.6 x 18.9mm",
    },
    // === Hệ điều hành ===
    {
      key: "os",
      label: "Hệ điều hành",
      type: "text",
      required: false,
      placeholder: "Windows 11 Home Single Language",
    },
    // === Cổng kết nối ===
    {
      key: "ports",
      label: "Cổng giao tiếp",
      type: "text",
      required: false,
      placeholder: "2x USB 3.2, 1x USB-C, 1x HDMI 2.1, 1x RJ45, 1x Audio Jack",
    },
    // === Kết nối không dây ===
    {
      key: "wifi",
      label: "Chuẩn WiFi",
      type: "text",
      required: false,
      placeholder: "Wi-Fi 6E 802.11ax / Killer™ Wi-Fi 6E",
    },
    {
      key: "bluetooth",
      label: "Bluetooth",
      type: "text",
      required: false,
      placeholder: "Bluetooth 5.3",
    },
    {
      key: "lan",
      label: "Chuẩn LAN",
      type: "text",
      required: false,
      placeholder: "10/100/1000 GbE LAN",
    },
    // === Thiết bị ngoại vi ===
    {
      key: "webcam",
      label: "Webcam",
      type: "text",
      required: false,
      placeholder: "FHD Camera / HD 720p",
    },
    {
      key: "keyboard",
      label: "Bàn phím",
      type: "text",
      required: false,
      placeholder: "Full-size backlit keyboard with numeric keypad",
    },
    {
      key: "audio",
      label: "Audio",
      type: "text",
      required: false,
      placeholder: "2x 2W Stereo Speakers / DTS:X Ultra",
    },
    // === Thiết kế ===
    {
      key: "color",
      label: "Màu sắc",
      type: "text",
      required: false,
      placeholder: "Steel Gray / Urban Silver",
    },
    {
      key: "material",
      label: "Chất liệu",
      type: "text",
      required: false,
      placeholder: "Cover A/C/D: Aluminum; Cover B: Plastic",
    },
    // === Bảo mật ===
    {
      key: "security",
      label: "Bảo mật",
      type: "text",
      required: false,
      placeholder: "Firmware TPM / Fingerprint Reader / BIOS Password",
    },
    // === Bảo hành ===
    {
      key: "warranty",
      label: "Bảo hành",
      type: "text",
      required: false,
      placeholder: "24 tháng",
    },
  ],

  // CPU
  [PRODUCT_CATEGORIES.CPU]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Intel Core i5-13400 / AMD Ryzen 5 7600",
    },
    {
      key: "generation",
      label: "Thế hệ",
      type: "text",
      required: false,
      placeholder: "Intel thế hệ 13 / AMD Zen 4",
    },
    {
      key: "socket",
      label: "Socket",
      type: "text",
      required: true,
      placeholder: "LGA 1700 / AM5",
    },
    // === Nhân & Luồng ===
    {
      key: "cores",
      label: "Số nhân",
      type: "text",
      required: true,
      placeholder: "10 (6P+4E) / 6",
    },
    {
      key: "threads",
      label: "Số luồng",
      type: "text",
      required: true,
      placeholder: "16 / 12",
    },
    {
      key: "performanceCores",
      label: "Số lõi hiệu năng (P-cores)",
      type: "text",
      required: false,
      placeholder: "6 lõi",
    },
    {
      key: "efficientCores",
      label: "Số lõi hiệu suất (E-cores)",
      type: "text",
      required: false,
      placeholder: "4 lõi",
    },
    // === Tốc độ ===
    {
      key: "baseClock",
      label: "Xung nhịp cơ bản",
      type: "text",
      required: true,
      placeholder: "2.5 GHz / 3.8 GHz",
    },
    {
      key: "boostClock",
      label: "Xung nhịp Turbo",
      type: "text",
      required: true,
      placeholder: "4.6 GHz / 5.1 GHz",
    },
    {
      key: "performanceClock",
      label: "Tốc độ lõi hiệu năng",
      type: "text",
      required: false,
      placeholder: "2.5 GHz Turbo up to 4.6 GHz",
    },
    {
      key: "efficientClock",
      label: "Tốc độ lõi hiệu suất",
      type: "text",
      required: false,
      placeholder: "1.8 GHz Turbo up to 3.3 GHz",
    },
    // === Bộ nhớ đệm ===
    {
      key: "cacheL2",
      label: "Bộ nhớ đệm L2",
      type: "text",
      required: false,
      placeholder: "9.5 MB / 6 MB",
    },
    {
      key: "cacheL3",
      label: "Bộ nhớ đệm L3",
      type: "text",
      required: true,
      placeholder: "20 MB / 32 MB",
    },
    {
      key: "totalCache",
      label: "Tổng Cache",
      type: "text",
      required: false,
      placeholder: "20 MB Intel Smart Cache",
    },
    // === TDP ===
    {
      key: "baseTDP",
      label: "Công suất cơ bản (TDP)",
      type: "text",
      required: false,
      placeholder: "65W",
    },
    {
      key: "maxTDP",
      label: "Công suất tối đa",
      type: "text",
      required: false,
      placeholder: "154W",
    },
    // === Bộ nhớ hỗ trợ ===
    {
      key: "memoryType",
      label: "Loại bộ nhớ hỗ trợ",
      type: "text",
      required: false,
      placeholder: "DDR5-4800 / DDR4-3200 / DDR5-5200",
    },
    {
      key: "maxMemory",
      label: "Dung lượng RAM tối đa",
      type: "text",
      required: false,
      placeholder: "128GB / 192GB",
    },
    {
      key: "memoryChannels",
      label: "Số kênh bộ nhớ",
      type: "text",
      required: false,
      placeholder: "2 kênh",
    },
    {
      key: "memoryBandwidth",
      label: "Băng thông bộ nhớ tối đa",
      type: "text",
      required: false,
      placeholder: "76.8 GB/s",
    },
    // === Đồ họa tích hợp ===
    {
      key: "integratedGraphics",
      label: "Đồ họa tích hợp",
      type: "text",
      required: false,
      placeholder: "Intel UHD 730 / AMD Radeon Graphics",
    },
    {
      key: "gpuBaseClock",
      label: "Tần số GPU cơ bản",
      type: "text",
      required: false,
      placeholder: "300 MHz",
    },
    {
      key: "gpuBoostClock",
      label: "Tần số GPU tối đa",
      type: "text",
      required: false,
      placeholder: "1.55 GHz",
    },
    {
      key: "gpuOutputs",
      label: "Đầu ra đồ họa",
      type: "text",
      required: false,
      placeholder: "eDP 1.4b, DP 1.4a, HDMI 2.1",
    },
    {
      key: "maxResolution",
      label: "Độ phân giải tối đa",
      type: "text",
      required: false,
      placeholder: "HDMI: 4096x2160@60Hz, DP: 7680x4320@60Hz",
    },
    {
      key: "directXSupport",
      label: "Hỗ trợ DirectX",
      type: "text",
      required: false,
      placeholder: "DirectX 12",
    },
    {
      key: "openGLSupport",
      label: "Hỗ trợ OpenGL",
      type: "text",
      required: false,
      placeholder: "OpenGL 4.5",
    },
    // === PCI Express ===
    {
      key: "pciVersion",
      label: "Phiên bản PCI Express",
      type: "text",
      required: false,
      placeholder: "PCIe 5.0 / PCIe 4.0",
    },
    {
      key: "pciLanes",
      label: "Số làn PCI Express",
      type: "text",
      required: false,
      placeholder: "20 lanes / 24 lanes",
    },
    {
      key: "pciConfig",
      label: "Cấu hình PCI Express",
      type: "text",
      required: false,
      placeholder: "Up to 1x16+4, 2x8+4",
    },
    // === Khác ===
    {
      key: "unlocked",
      label: "Mở khóa ép xung",
      type: "select",
      options: ["Có (K/KF/X/XT)", "Không"],
      required: false,
    },
    {
      key: "coolerIncluded",
      label: "Tản nhiệt đi kèm",
      type: "text",
      required: false,
      placeholder: "Không có / AMD Wraith Stealth",
    },
    {
      key: "architecture",
      label: "Kiến trúc",
      type: "text",
      required: false,
      placeholder: "Raptor Lake / Zen 4",
    },
    {
      key: "manufacturing",
      label: "Tiến trình sản xuất",
      type: "text",
      required: false,
      placeholder: "Intel 7 (10nm) / TSMC 5nm",
    },
  ],

  // Mainboard
  [PRODUCT_CATEGORIES.MAINBOARD]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "GIGABYTE X299 AORUS Gaming 7 Pro",
    },
    {
      key: "chipset",
      label: "Chipset",
      type: "text",
      required: true,
      placeholder: "Intel X299 / Z890 / B760",
    },
    {
      key: "socket",
      label: "Socket",
      type: "text",
      required: true,
      placeholder: "LGA 2066 / LGA 1851 / AM5",
    },
    {
      key: "formFactor",
      label: "Form Factor",
      type: "select",
      options: ["E-ATX", "ATX", "Micro-ATX", "Mini-ITX"],
      required: true,
    },
    // === RAM ===
    {
      key: "ramSlots",
      label: "Số khe RAM",
      type: "text",
      required: true,
      placeholder: "4 / 8",
    },
    {
      key: "ramType",
      label: "Loại RAM",
      type: "text",
      required: true,
      placeholder: "DDR5 / DDR4",
    },
    {
      key: "maxRam",
      label: "RAM tối đa",
      type: "text",
      required: false,
      placeholder: "256GB",
    },
    {
      key: "ramSpeed",
      label: "Tốc độ RAM",
      type: "text",
      required: false,
      placeholder: "DDR5-9200 (OC) / DDR4-4333 (OC)",
    },
    // === Storage ===
    {
      key: "m2Slots",
      label: "Khe M.2",
      type: "text",
      required: false,
      placeholder: "3x M.2 (1x PCIe 5.0, 2x PCIe 4.0)",
    },
    {
      key: "sataSlots",
      label: "Cổng SATA",
      type: "text",
      required: false,
      placeholder: "4 / 6 / 8",
    },
    // === Expansion ===
    {
      key: "pciSlots",
      label: "Khe PCI Express",
      type: "text",
      required: false,
      placeholder: "2x PCIe 5.0 x16, 1x PCIe 4.0 x1",
    },
    // === Audio & LAN ===
    {
      key: "audioChip",
      label: "Audio",
      type: "text",
      required: false,
      placeholder: "Realtek ALC1220 7.1-Channel",
    },
    {
      key: "lan",
      label: "LAN",
      type: "text",
      required: false,
      placeholder: "Intel 2.5GbE / Killer 5GbE",
    },
    {
      key: "wifi",
      label: "Wi-Fi",
      type: "text",
      required: false,
      placeholder: "Wi-Fi 7 (BE1750x) / Wi-Fi 6E",
    },
    {
      key: "bluetooth",
      label: "Bluetooth",
      type: "text",
      required: false,
      placeholder: "Bluetooth 5.4 / 5.3",
    },
    // === Connectivity ===
    {
      key: "usb",
      label: "USB",
      type: "text",
      required: false,
      placeholder: "4x USB 3.2 Gen2, 6x USB 3.2 Gen1, 2x USB 2.0",
    },
    {
      key: "thunderbolt",
      label: "Thunderbolt",
      type: "text",
      required: false,
      placeholder: "2x Thunderbolt 4 (40Gbps)",
    },
    // === Other ===
    {
      key: "rgb",
      label: "RGB",
      type: "text",
      required: false,
      placeholder: "3x ARGB Header, 1x RGB Header",
    },
    {
      key: "features",
      label: "Tính năng đặc biệt",
      type: "text",
      required: false,
      placeholder: "Q-Flash Plus, Dual BIOS, EZ Debug LED",
    },
  ],
  // RAM
  [PRODUCT_CATEGORIES.RAM]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "V-Color Skywalker Plus / Kingston Fury Beast",
    },
    {
      key: "type",
      label: "Loại RAM",
      type: "select",
      options: ["DDR3", "DDR4", "DDR5"],
      required: true,
    },
    {
      key: "capacity",
      label: "Dung lượng",
      type: "text",
      required: true,
      placeholder: "16GB / 32GB",
    },
    {
      key: "modules",
      label: "Số module (Kit)",
      type: "select",
      options: ["1x", "2x (Kit)", "4x (Kit)"],
      required: true,
    },
    {
      key: "speed",
      label: "Tốc độ Bus",
      type: "text",
      required: true,
      placeholder: "3600MHz / 6000MHz",
    },
    {
      key: "cas",
      label: "CAS Latency",
      type: "text",
      required: false,
      placeholder: "CL18 / CL36-38-38",
    },
    {
      key: "voltage",
      label: "Điện áp",
      type: "text",
      required: false,
      placeholder: "1.35V / 1.1V - 1.35V",
    },
    {
      key: "formFactor",
      label: "Kiểu dáng",
      type: "select",
      options: ["DIMM (Desktop)", "SO-DIMM (Laptop)", "CUDIMM"],
      required: false,
    },
    {
      key: "xmpSupport",
      label: "Hỗ trợ XMP/EXPO",
      type: "text",
      required: false,
      placeholder: "Intel XMP 3.0 / AMD EXPO",
    },
    {
      key: "ecc",
      label: "ECC",
      type: "select",
      options: ["Có", "Không"],
      required: false,
    },
    {
      key: "rgb",
      label: "LED RGB",
      type: "select",
      options: ["Có", "Không"],
      required: false,
    },
    {
      key: "heatsink",
      label: "Tản nhiệt",
      type: "text",
      required: false,
      placeholder: "Aluminum Heatsink / Low-Profile",
    },
    {
      key: "color",
      label: "Màu sắc",
      type: "text",
      required: false,
      placeholder: "Đen / Trắng / Bạc",
    },
  ],

  // VGA (Card đồ họa)
  [PRODUCT_CATEGORIES.VGA]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "ASUS Dual GeForce RTX 5050",
    },
    {
      key: "chipset",
      label: "GPU Chipset",
      type: "text",
      required: true,
      placeholder: "NVIDIA GeForce RTX 5050 / AMD Radeon RX 7600",
    },
    // === Memory ===
    {
      key: "vram",
      label: "Bộ nhớ (VRAM)",
      type: "text",
      required: true,
      placeholder: "8GB GDDR6 / 8GB GDDR7",
    },
    {
      key: "memoryType",
      label: "Loại bộ nhớ",
      type: "select",
      options: ["GDDR6", "GDDR6X", "GDDR7"],
      required: false,
    },
    {
      key: "busWidth",
      label: "Memory Bus",
      type: "text",
      required: false,
      placeholder: "128-bit / 256-bit",
    },
    {
      key: "memorySpeed",
      label: "Tốc độ bộ nhớ",
      type: "text",
      required: false,
      placeholder: "20 Gbps / 28 Gbps",
    },
    // === Core ===
    {
      key: "cudaCores",
      label: "CUDA Cores / Stream Processors",
      type: "text",
      required: false,
      placeholder: "2560 CUDA Cores / 2048 Stream Processors",
    },
    {
      key: "boostClock",
      label: "Boost Clock",
      type: "text",
      required: false,
      placeholder: "2677 MHz / 2707 MHz (OC)",
    },
    {
      key: "baseClock",
      label: "Base Clock",
      type: "text",
      required: false,
      placeholder: "2400 MHz",
    },
    // === Performance ===
    {
      key: "aiPerformance",
      label: "AI Performance",
      type: "text",
      required: false,
      placeholder: "439 TOPS",
    },
    // === Power ===
    {
      key: "tdp",
      label: "TDP",
      type: "text",
      required: false,
      placeholder: "145W",
    },
    {
      key: "recommendedPSU",
      label: "Nguồn khuyến nghị",
      type: "text",
      required: false,
      placeholder: "550W",
    },
    {
      key: "powerConnectors",
      label: "Nguồn phụ",
      type: "text",
      required: false,
      placeholder: "1x 8-pin / 1x 12VHPWR",
    },
    // === Display ===
    {
      key: "outputs",
      label: "Cổng xuất hình",
      type: "text",
      required: false,
      placeholder: "3x DisplayPort 2.1b, 1x HDMI 2.1b",
    },
    {
      key: "maxResolution",
      label: "Độ phân giải tối đa",
      type: "text",
      required: false,
      placeholder: "7680 x 4320 (8K)",
    },
    {
      key: "maxDisplays",
      label: "Số màn hình hỗ trợ",
      type: "text",
      required: false,
      placeholder: "4",
    },
    // === Interface ===
    {
      key: "pciInterface",
      label: "Giao tiếp PCI",
      type: "text",
      required: false,
      placeholder: "PCI Express 5.0 x8 / PCIe 4.0 x16",
    },
    // === Cooling & Design ===
    {
      key: "coolingSystem",
      label: "Hệ thống làm mát",
      type: "text",
      required: false,
      placeholder: "Dual Fan / Triple Fan / AIO Liquid",
    },
    {
      key: "slotSize",
      label: "Kích thước slot",
      type: "text",
      required: false,
      placeholder: "2.5 Slot / 3 Slot",
    },
    {
      key: "dimensions",
      label: "Kích thước (DxRxC)",
      type: "text",
      required: false,
      placeholder: "268 x 120 x 50 mm",
    },
    // === Features ===
    {
      key: "rgb",
      label: "RGB",
      type: "select",
      options: ["Có", "Không"],
      required: false,
    },
    {
      key: "backplate",
      label: "Backplate",
      type: "select",
      options: ["Có", "Không"],
      required: false,
    },
    {
      key: "features",
      label: "Tính năng đặc biệt",
      type: "text",
      required: false,
      placeholder: "Ray Tracing, DLSS 4, DirectX 12 Ultimate",
    },
  ],
  [PRODUCT_CATEGORIES.STORAGE]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Samsung 980 PRO / WD Blue",
    },
    {
      key: "storageType", // ✅ NEW: Phân biệt SSD/HDD
      label: "Loại ổ cứng",
      type: "select",
      options: ["SSD", "HDD"],
      required: true,
    },
    {
      key: "capacity",
      label: "Dung lượng",
      type: "select",
      options: [
        "128GB",
        "256GB",
        "512GB",
        "1TB",
        "2TB",
        "4TB",
        "8TB",
        "10TB",
        "12TB",
        "14TB",
        "18TB",
      ],
      required: false,
    },
    {
      key: "formFactor",
      label: "Form Factor",
      type: "select",
      options: ["M.2 2280", "M.2 2260", "M.2 2242", "2.5 inch", "3.5 inch"],
      required: false,
    },
    {
      key: "interface",
      label: "Giao tiếp",
      type: "select",
      options: [
        "PCIe 5.0 x4",
        "PCIe 4.0 x4",
        "PCIe 3.0 x4",
        "SATA III",
        "SATA II",
      ],
      required: false,
    },
    // ✅ SSD-specific fields
    {
      key: "nandType",
      label: "Loại NAND (SSD)",
      type: "select",
      options: ["TLC", "QLC", "MLC", "SLC"],
      required: false,
      // ✅ Chỉ hiện khi storageType = SSD
      showIf: (specs) => specs.storageType === "SSD",
    },
    {
      key: "controller",
      label: "Controller (SSD)",
      type: "text",
      required: false,
      placeholder: "Phison E18 / Samsung Elpis",
      showIf: (specs) => specs.storageType === "SSD",
    },
    {
      key: "readSpeed",
      label: "Tốc độ đọc (SSD)",
      type: "text",
      required: false,
      placeholder: "7000 MB/s",
      showIf: (specs) => specs.storageType === "SSD",
    },
    {
      key: "writeSpeed",
      label: "Tốc độ ghi (SSD)",
      type: "text",
      required: false,
      placeholder: "5000 MB/s",
      showIf: (specs) => specs.storageType === "SSD",
    },
    {
      key: "tbw",
      label: "TBW (Tuổi thọ ghi - SSD)",
      type: "text",
      required: false,
      placeholder: "600 TBW",
      showIf: (specs) => specs.storageType === "SSD",
    },
    // ✅ HDD-specific fields
    {
      key: "rpm",
      label: "Tốc độ vòng quay (HDD)",
      type: "select",
      options: ["5400 RPM", "7200 RPM", "10000 RPM"],
      required: false,
      showIf: (specs) => specs.storageType === "HDD",
    },
    {
      key: "cache",
      label: "Cache (HDD)",
      type: "select",
      options: ["32MB", "64MB", "128MB", "256MB"],
      required: false,
      showIf: (specs) => specs.storageType === "HDD",
    },
    // Common fields
    {
      key: "warranty",
      label: "Bảo hành",
      type: "text",
      required: false,
      placeholder: "5 năm / 10 năm",
    },
  ],

  // PSU (Nguồn)
  [PRODUCT_CATEGORIES.PSU]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "ASUS ROG Strix 1600W / FSP HV PRO 550W",
    },
    {
      key: "wattage",
      label: "Công suất",
      type: "text",
      required: true,
      placeholder: "550W / 750W / 1000W / 1600W",
    },
    {
      key: "certification",
      label: "Chứng nhận hiệu suất",
      type: "select",
      options: [
        "80 Plus",
        "80 Plus Bronze",
        "80 Plus Silver",
        "80 Plus Gold",
        "80 Plus Platinum",
        "80 Plus Titanium",
      ],
      required: true,
    },
    {
      key: "modular",
      label: "Dây rời",
      type: "select",
      options: ["Non-Modular", "Semi-Modular", "Full-Modular"],
      required: true,
    },
    {
      key: "atxStandard",
      label: "Chuẩn ATX",
      type: "text",
      required: false,
      placeholder: "ATX 3.0 / ATX 3.1 / ATX12V",
    },
    {
      key: "pfc",
      label: "PFC",
      type: "text",
      required: false,
      placeholder: "PFC hoạt động (Active PFC)",
    },
    // === Cooling ===
    {
      key: "fan",
      label: "Quạt làm mát",
      type: "text",
      required: false,
      placeholder: "135mm Axial-tech / 120mm Hydro Dynamic",
    },
    {
      key: "fanMode",
      label: "Chế độ quạt",
      type: "text",
      required: false,
      placeholder: "0dB (Fanless mode) / Eco mode",
    },
    // === Connectors (Gộp chung để dễ nhập) ===
    {
      key: "connectors",
      label: "Cổng kết nối",
      type: "text",
      required: false,
      placeholder:
        "1x MB 24-pin, 2x CPU 8-pin, 1x PCIe 16-pin, 4x PCIe 8-pin, 6x SATA",
    },
    {
      key: "pcie5Support",
      label: "Hỗ trợ PCIe 5.0",
      type: "select",
      options: ["Có (16-pin)", "Không"],
      required: false,
    },
    // === Build Quality ===
    {
      key: "capacitor",
      label: "Tụ điện",
      type: "text",
      required: false,
      placeholder: "Tụ điện Nhật Bản / Japanese Capacitors",
    },
    {
      key: "protections",
      label: "Bảo vệ",
      type: "text",
      required: false,
      placeholder: "OPP, OVP, UVP, SCP, OCP, OTP",
    },
    // === Features ===
    {
      key: "features",
      label: "Tính năng đặc biệt",
      type: "text",
      required: false,
      placeholder: "OLED Display, RGB Aura Sync, Zero-noise",
    },
    // === Physical ===
    {
      key: "dimensions",
      label: "Kích thước (DxRxC)",
      type: "text",
      required: false,
      placeholder: "160 x 150 x 86 mm",
    },
    {
      key: "warranty",
      label: "Bảo hành",
      type: "text",
      required: false,
      placeholder: "3 năm / 5 năm / 10 năm",
    },
  ],

  // Case (Vỏ máy)
  [PRODUCT_CATEGORIES.CASE]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "ASUS A21 Case / NZXT H5 Flow",
    },
    {
      key: "formFactor",
      label: "Kích thước (Form Factor)",
      type: "select",
      options: ["Full Tower", "Mid Tower", "Mini Tower", "Mini-ITX"],
      required: true,
    },
    {
      key: "mainboardSupport",
      label: "Bo mạch chủ hỗ trợ",
      type: "text",
      required: true,
      placeholder: "ATX, Micro-ATX, Mini-ITX",
    },
    {
      key: "material",
      label: "Chất liệu",
      type: "text",
      required: false,
      placeholder: "SPCC Steel, Tempered Glass / Thép SPCC, Kính cường lực",
    },
    // === Expansion ===
    {
      key: "expansionSlots",
      label: "Khe mở rộng (Expansion Slots)",
      type: "text",
      required: false,
      placeholder: "5 / 7",
    },
    {
      key: "driveBays",
      label: "Khay ổ cứng (Drive Bays)",
      type: "text",
      required: false,
      placeholder: '3x 2.5" SSD, 1x 3.5" HDD',
    },
    // === Cooling Support ===
    {
      key: "fanSupport",
      label: "Quạt hỗ trợ (Fan Support)",
      type: "text",
      required: false,
      placeholder: "Trước: 3x 120mm / 2x 140mm, Trên: 2x 120mm, Sau: 1x 120mm",
    },
    {
      key: "radiatorSupport",
      label: "Tản nhiệt nước hỗ trợ (Radiator Support)",
      type: "text",
      required: false,
      placeholder: "Trước: 360mm, Trên: 240mm, Sau: 120mm",
    },
    {
      key: "maxCpuCoolerHeight",
      label: "Chiều cao tản nhiệt CPU tối đa (Max CPU Cooler Height)",
      type: "text",
      required: false,
      placeholder: "165mm / 170mm",
    },
    // === Clearance ===
    {
      key: "maxGpuLength",
      label: "Độ dài VGA tối đa (Max GPU Length)",
      type: "text",
      required: false,
      placeholder: "380mm / 363mm",
    },
    {
      key: "maxPsuLength",
      label: "Độ dài nguồn tối đa (Max PSU Length)",
      type: "text",
      required: false,
      placeholder: "210mm / 180mm",
    },
    // === Front I/O ===
    {
      key: "frontIO",
      label: "Cổng I/O phía trước (Front I/O)",
      type: "text",
      required: false,
      placeholder: "1x USB-C 3.2 Gen2, 1x USB-A 3.2 Gen1, Audio/Mic",
    },
    // === Dimensions & Weight ===
    {
      key: "dimensions",
      label: "Kích thước (DxRxC) (Dimensions)",
      type: "text",
      required: false,
      placeholder: "430 x 220 x 465 mm",
    },
    {
      key: "weight",
      label: "Trọng lượng (Weight)",
      type: "text",
      required: false,
      placeholder: "7.3 kg / 5 kg",
    },
    // === Features ===
    {
      key: "rgb",
      label: "Đèn RGB",
      type: "select",
      options: ["Có", "Không"],
      required: false,
    },
    {
      key: "sidePanel",
      label: "Panel cạnh (Side Panel)",
      type: "text",
      required: false,
      placeholder: "Tempered Glass / Kính cường lực",
    },
    {
      key: "dustFilter",
      label: "Lọc bụi (Dust Filter)",
      type: "text",
      required: false,
      placeholder: "Top, Front, Bottom / Trên, Trước, Dưới",
    },
  ],
  // Cooling (Tản nhiệt)
  [PRODUCT_CATEGORIES.COOLING]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Cooler Master MasterLiquid Lite MLW-D24M-A18PZ-R1",
    },
    {
      key: "type",
      label: "Loại tản nhiệt",
      type: "select",
      options: [
        "Air Cooler (Khí)",
        "AIO Liquid (Nước AIO)",
        "Custom Loop (Nước tùy chỉnh)",
      ],
      required: true,
    },
    // === Radiator (cho AIO) ===
    {
      key: "radiatorSize",
      label: "Kích thước két nước (Radiator Size)",
      type: "text",
      required: false,
      placeholder: "240mm / 280mm / 360mm",
    },
    {
      key: "radiatorDimensions",
      label: "Kích thước radiator (DxRxC)",
      type: "text",
      required: false,
      placeholder: "277 x 119.6 x 27.2 mm",
    },
    {
      key: "radiatorMaterial",
      label: "Vật liệu radiator",
      type: "text",
      required: false,
      placeholder: "Nhôm (Aluminum)",
    },
    // === Fan ===
    {
      key: "fanSize",
      label: "Kích thước quạt (Fan Size)",
      type: "text",
      required: false,
      placeholder: "120mm / 140mm",
    },
    {
      key: "fanCount",
      label: "Số lượng quạt (Fan Count)",
      type: "text",
      required: false,
      placeholder: "2 quạt / 3 quạt",
    },
    {
      key: "fanSpeed",
      label: "Tốc độ quạt (Fan Speed)",
      type: "text",
      required: false,
      placeholder: "650-1800 RPM",
    },
    {
      key: "fanNoise",
      label: "Độ ồn quạt (Fan Noise)",
      type: "text",
      required: false,
      placeholder: "6 - 30 dBA",
    },
    {
      key: "fanAirflow",
      label: "Lưu lượng gió (Airflow)",
      type: "text",
      required: false,
      placeholder: "71.93 CFM",
    },
    // === Pump (cho AIO) ===
    {
      key: "pumpNoise",
      label: "Độ ồn bơm (Pump Noise)",
      type: "text",
      required: false,
      placeholder: "< 10 dBA / 12 dBA",
    },
    {
      key: "pumpLifespan",
      label: "Tuổi thọ bơm (Pump Lifespan)",
      type: "text",
      required: false,
      placeholder: "70,000 giờ",
    },
    // === Heatsink (cho Air Cooler) ===
    {
      key: "height",
      label: "Chiều cao tản nhiệt (Cooler Height)",
      type: "text",
      required: false,
      placeholder: "158mm / 165mm",
    },
    {
      key: "heatpipeMaterial",
      label: "Vật liệu ống nhiệt (Heatpipe Material)",
      type: "text",
      required: false,
      placeholder: "Đồng (Copper)",
    },
    {
      key: "heatpipeCount",
      label: "Số ống nhiệt (Heatpipe Count)",
      type: "text",
      required: false,
      placeholder: "4 / 6 / 8",
    },
    // === Compatibility ===
    {
      key: "socketSupport",
      label: "Socket hỗ trợ (Socket Support)",
      type: "text",
      required: false,
      placeholder: "LGA1700, LGA1200, AM5, AM4",
    },
    {
      key: "tdp",
      label: "TDP hỗ trợ",
      type: "text",
      required: false,
      placeholder: "180W / 250W",
    },
    // === Features ===
    {
      key: "rgb",
      label: "Đèn RGB",
      type: "text",
      required: false,
      placeholder: "Addressable RGB / ARGB Gen 2",
    },
    {
      key: "color",
      label: "Màu sắc",
      type: "text",
      required: false,
      placeholder: "Đen / Trắng",
    },
    {
      key: "warranty",
      label: "Bảo hành",
      type: "text",
      required: false,
      placeholder: "2 năm / 3 năm",
    },
  ],

  // Monitor - ✅ ĐÃ CẬP NHẬT ĐẦY ĐỦ
  [PRODUCT_CATEGORIES.MONITOR]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "AOC 24G2",
    },
    {
      key: "size",
      label: "Kích thước",
      type: "text",
      required: true,
      placeholder: "24 inch",
    },
    {
      key: "resolution",
      label: "Độ phân giải",
      type: "text",
      required: true,
      placeholder: "Full HD (1920x1080)",
    },
    {
      key: "panel",
      label: "Tấm nền",
      type: "select",
      options: ["IPS", "VA", "TN", "OLED", "Mini-LED"],
      required: true,
    },
    {
      key: "screenType",
      label: "Kiểu màn hình",
      type: "text",
      required: true,
      placeholder: "Phẳng / Cong 1800R",
    },
    {
      key: "refreshRate",
      label: "Tần số quét",
      type: "text",
      required: true,
      placeholder: "180 Hz",
    },
    {
      key: "responseTime",
      label: "Thời gian phản hồi",
      type: "text",
      required: true,
      placeholder: "1ms GtG",
    },
    {
      key: "brightness",
      label: "Độ sáng (Typ.)",
      type: "text",
      required: false,
      placeholder: "250 cd/m²",
    },
    {
      key: "colorSpace",
      label: "Không gian màu (sRGB)",
      type: "text",
      required: false,
      placeholder: "135%",
    },
    {
      key: "ports",
      label: "Cổng kết nối",
      type: "text",
      required: false,
      placeholder: "1x HDMI; 1x DisplayPort 1.4",
    },
    {
      key: "vesaMount",
      label: "Tương thích VESA",
      type: "text",
      required: false,
      placeholder: "100 x 100mm",
    },
    {
      key: "flickerFree",
      label: "Khử nhấp nháy",
      type: "select",
      options: ["Có", "Không"],
      required: false,
    },
    {
      key: "warranty",
      label: "Bảo hành",
      type: "text",
      required: false,
      placeholder: "36 Tháng",
    },
    {
      key: "accessories",
      label: "Phụ kiện trong hộp",
      type: "text",
      required: false,
      placeholder: "Dây nguồn; dây HDMI; dây DisplayPort",
    },
    // === THÔNG SỐ BỔ SUNG ===
    {
      key: "adaptiveSync",
      label: "Công nghệ đồng bộ hóa",
      type: "text",
      required: false,
      placeholder: "G-SYNC / FreeSync",
    },
    {
      key: "aspectRatio",
      label: "Tỉ lệ khung hình",
      type: "text",
      required: false,
      placeholder: "16:9 / 21:9 / 32:9",
    },
    {
      key: "displayColors",
      label: "Màu hiển thị",
      type: "text",
      required: false,
      placeholder: "16.7M (8 bit) / 1073.7M (10 bit)",
    },
    {
      key: "contrastRatio",
      label: "Tỷ lệ tương phản (Typ.)",
      type: "text",
      required: false,
      placeholder: "1000:1 / 1,500,000:1",
    },
    {
      key: "surfaceType",
      label: "Bề mặt hiển thị",
      type: "select",
      options: ["Chống lóa", "Bóng"],
      required: false,
    },
    {
      key: "mechanicalDesign",
      label: "Thiết kế cơ học",
      type: "text",
      required: false,
      placeholder: "Nghiêng: -5°~+20°; Quay: ±15°; Điều chỉnh độ cao: 0-100mm",
    },
    {
      key: "weight",
      label: "Trọng lượng",
      type: "text",
      required: false,
      placeholder: "5.2 kg",
    },
    {
      key: "packageDimensions",
      label: "Kích thước đóng gói",
      type: "text",
      required: false,
      placeholder: "60 x 50 x 20 cm",
    },
  ],

  // Keyboard
  [PRODUCT_CATEGORIES.KEYBOARD]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Razer BlackWidow V4 / Logitech G Pro X",
    },
    {
      key: "type",
      label: "Loại switch",
      type: "select",
      options: [
        "Mechanical (Cơ)",
        "Membrane (Màng)",
        "Optical (Quang học)",
        "Hybrid",
      ],
      required: true,
    },
    {
      key: "switch",
      label: "Switch",
      type: "text",
      required: false,
      placeholder: "Cherry MX Red / Razer Green / Gateron Yellow",
    },
    {
      key: "switchType",
      label: "Loại switch (âm thanh)",
      type: "text",
      required: false,
      placeholder: "Clicky / Linear / Tactile",
    },
    {
      key: "layout",
      label: "Layout",
      type: "select",
      options: ["Full-size (100%)", "TKL (80%)", "75%", "65%", "60%", "40%"],
      required: true,
    },
    {
      key: "keycap",
      label: "Keycap",
      type: "text",
      required: false,
      placeholder: "Doubleshot ABS / PBT / Doubleshot PBT",
    },
    {
      key: "connection",
      label: "Kết nối",
      type: "select",
      options: [
        "Có dây (Wired)",
        "Không dây (Wireless)",
        "2.4GHz + Bluetooth",
        "Tri-mode (USB + 2.4G + BT)",
      ],
      required: true,
    },
    {
      key: "cable",
      label: "Loại dây",
      type: "text",
      required: false,
      placeholder: "USB Type-C Detachable / Braided Cable",
    },
    {
      key: "battery",
      label: "Pin (nếu wireless)",
      type: "text",
      required: false,
      placeholder: "2000mAh / 40 giờ sử dụng",
    },
    {
      key: "rgb",
      label: "Đèn RGB",
      type: "text",
      required: false,
      placeholder: "Per-key RGB / Single-color / Razer Chroma RGB",
    },
    {
      key: "software",
      label: "Phần mềm hỗ trợ",
      type: "text",
      required: false,
      placeholder: "Razer Synapse / G Hub / VIA / QMK",
    },
    {
      key: "hotSwap",
      label: "Hot-swap",
      type: "select",
      options: ["Có (Hot-swappable)", "Không"],
      required: false,
    },
    {
      key: "features",
      label: "Tính năng đặc biệt",
      type: "text",
      required: false,
      placeholder: "Snap Tap, N-Key Rollover, Media Keys, Wrist Rest",
    },
    {
      key: "material",
      label: "Chất liệu",
      type: "text",
      required: false,
      placeholder: "Aluminum Frame / Plastic / Metal Plate",
    },
    {
      key: "weight",
      label: "Trọng lượng",
      type: "text",
      required: false,
      placeholder: "1.2 kg / 850g",
    },
    {
      key: "warranty",
      label: "Bảo hành",
      type: "text",
      required: false,
      placeholder: "12 tháng / 24 tháng",
    },
  ],

  // Mouse
  [PRODUCT_CATEGORIES.MOUSE]: [
    {
      key: "model",
      label: "Model",
      type: "text",
      required: true,
      placeholder: "Logitech G502 HERO / Razer DeathAdder V3",
    },
    {
      key: "sensor",
      label: "Mắt đọc (Sensor)",
      type: "text",
      required: false,
      placeholder: "Mercury Sensor / HERO 25K / Focus Pro 30K",
    },
    {
      key: "dpi",
      label: "DPI",
      type: "text",
      required: false,
      placeholder: "8000 / 16000 / 100-30000",
    },
    {
      key: "ips",
      label: "IPS (Tốc độ theo dõi)",
      type: "text",
      required: false,
      placeholder: "200 IPS / 400 IPS / 650 IPS",
    },
    {
      key: "acceleration",
      label: "Gia tốc (Acceleration)",
      type: "text",
      required: false,
      placeholder: "30g / 40g / 50g",
    },
    {
      key: "pollingRate",
      label: "Tần số phản hồi (Polling Rate)",
      type: "text",
      required: false,
      placeholder: "1000Hz / 2000Hz / 4000Hz / 8000Hz",
    },
    {
      key: "buttons",
      label: "Số lượng nút bấm",
      type: "text",
      required: false,
      placeholder: "5 / 6 / 7 / 11",
    },
    {
      key: "switch",
      label: "Switch (Nút bấm)",
      type: "text",
      required: false,
      placeholder: "Omron / Kailh GM 8.0 / Razer Optical",
    },
    {
      key: "switchLifespan",
      label: "Tuổi thọ switch",
      type: "text",
      required: false,
      placeholder: "50 triệu lần nhấn / 80 triệu lần nhấn",
    },
    {
      key: "connection",
      label: "Kết nối",
      type: "select",
      options: [
        "USB (Có dây)",
        "Wireless 2.4GHz",
        "Bluetooth",
        "2.4GHz + Bluetooth",
        "Tri-mode",
      ],
      required: false,
    },
    {
      key: "cable",
      label: "Loại dây",
      type: "text",
      required: false,
      placeholder: "Speedflex Cable / Paracord / Detachable",
    },
    {
      key: "cableLength",
      label: "Độ dài dây (cm)",
      type: "text",
      required: false,
      placeholder: "180cm / 210cm",
    },
    {
      key: "battery",
      label: "Pin (nếu wireless)",
      type: "text",
      required: false,
      placeholder: "650mAh / 80 giờ / AAA",
    },
    {
      key: "design",
      label: "Thiết kế",
      type: "text",
      required: false,
      placeholder: "Đối xứng (Ambidextrous) / Thuận tay phải (Ergonomic)",
    },
    {
      key: "weight",
      label: "Trọng lượng",
      type: "text",
      required: false,
      placeholder: "85g (không cable) / 59g",
    },
    {
      key: "dimensions",
      label: "Kích thước (DxRxC)",
      type: "text",
      required: false,
      placeholder: "116.6 x 62.15 x 38.2 mm",
    },
    {
      key: "material",
      label: "Chất liệu vỏ",
      type: "text",
      required: false,
      placeholder: "Nhựa ABS / Nhựa PC / Aluminum",
    },
    {
      key: "grip",
      label: "Grip Surface",
      type: "text",
      required: false,
      placeholder: "Textured / Smooth / Rubber Grips",
    },
    {
      key: "rgb",
      label: "Đèn LED",
      type: "text",
      required: false,
      placeholder: "RGB Lightsync / Razer Chroma / Single-color",
    },
    {
      key: "software",
      label: "Phần mềm",
      type: "text",
      required: false,
      placeholder: "Logitech G-Hub / Razer Synapse / X-Mouse",
    },
    {
      key: "color",
      label: "Màu sắc",
      type: "text",
      required: false,
      placeholder: "Đen / Trắng / Hồng",
    },
    {
      key: "warranty",
      label: "Bảo hành",
      type: "text",
      required: false,
      placeholder: "12 tháng / 24 tháng",
    },
  ],
  // 🆕 GHẾ GAMING/VĂN PHÒNG
  [PRODUCT_CATEGORIES.CHAIR]: [
    {
      key: "material",
      label: "Chất liệu",
      type: "text",
      required: true,
      placeholder: "VD: Lưới Gentry, Da PU, Vải nỉ",
    },
    {
      key: "armrest",
      label: "Tay vịn",
      type: "text",
      required: false,
      placeholder: "VD: Kê tay 3D, 4D điều chỉnh, Cố định",
    },
    {
      key: "mechanism",
      label: "Cơ chế",
      type: "text",
      required: false,
      placeholder: "VD: Ngả lưng True Tilt, Piston Class 3",
    },
    {
      key: "max_load",
      label: "Tải trọng tối đa",
      type: "text",
      required: false,
      placeholder: "VD: 120kg, 150kg",
    },
    {
      key: "dimensions",
      label: "Kích thước",
      type: "text",
      required: false,
      placeholder: "VD: 113-119 x 64 x 64 cm",
    },
    {
      key: "wheel_size",
      label: "Kích thước bánh xe",
      type: "text",
      required: false,
      placeholder: "VD: 64cm, 60mm PU",
    },
  ],

  [PRODUCT_CATEGORIES.HEADPHONE]: [
    {
      key: "connection",
      label: "Kết nối",
      type: "text",
      required: true,
      placeholder: "VD: Không dây 2.4GHz, USB-C, Jack 3.5mm",
    },
    {
      key: "driver",
      label: "Màng loa",
      type: "text",
      required: false,
      placeholder: "VD: 53mm, 40mm, 50mm Neodymium",
    },
    {
      key: "surround",
      label: "Âm thanh vòm",
      type: "text",
      required: false,
      placeholder: "VD: 7.1, 5.1, Stereo 2.0",
    },
    {
      key: "battery",
      label: "Thời lượng pin",
      type: "text",
      required: false,
      placeholder: "VD: 120 giờ, 30 giờ, Không dây",
    },
    {
      key: "frequency",
      label: "Tần số đáp ứng",
      type: "text",
      required: false,
      placeholder: "VD: 10Hz-21kHz, 20Hz-20kHz",
    },
    {
      key: "wireless_range",
      label: "Phạm vi không dây",
      type: "text",
      required: false,
      placeholder: "VD: Lên đến 20m, 15m",
    },
  ],
  // 🆕 LOA / SPEAKER
  [PRODUCT_CATEGORIES.SPEAKER]: [
    {
      key: "power",
      label: "Công suất",
      type: "text",
      required: true,
      placeholder: "VD: 21W+21W, 50W, 100W RMS",
    },
    {
      key: "driver",
      label: "Cấu hình củ loa",
      type: "text",
      required: false,
      placeholder: "VD: Tweeter 1-inch/Bass 4-inch, 2-way",
    },
    {
      key: "frequency",
      label: "Đáp tuyến tần số",
      type: "text",
      required: false,
      placeholder: "VD: 60Hz-20KHz, 50Hz-22KHz",
    },
    {
      key: "connection",
      label: "Kết nối",
      type: "text",
      required: false,
      placeholder: "VD: Bluetooth, TRS/RCA/AUX, USB",
    },
    {
      key: "type",
      label: "Loại loa",
      type: "text",
      required: false,
      placeholder: "VD: 2.0, 2.1, 5.1, Soundbar, Bluetooth",
    },
  ],
  //phụ kiện
  [PRODUCT_CATEGORIES.ACCESSORY]: [],
  // 🆕 PHẦN MỀM
  [PRODUCT_CATEGORIES.SOFTWARE]: [],
};
